# Generated by Django 4.0.2 on 2022-04-17 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('roll', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Roll Number')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, verbose_name='Gender')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel_id', models.IntegerField(verbose_name='Hostel')),
                ('time', models.DateTimeField(verbose_name='Entry Time')),
                ('activity', models.CharField(choices=[('EN', 'Entry'), ('EX', 'Exit')], max_length=2, verbose_name='Activity')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='entry_system.person')),
            ],
        ),
    ]
